FROM python:3.11-slim

# Install system dependencies
RUN apt-get update && apt-get install -y \
    ffmpeg \
    libsm6 \
    libxext6 \
    libxrender-dev \
    libglib2.0-0 \
    libgl1-mesa-glx \
    libgtk-3-0 \
    libcanberra-gtk3-module \
    libcanberra-gtk3-0 \
    libcanberra-gtk-module \
    libcanberra-gtk0 \
    libcanberra-dev \
    libcanberra-gtk-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk0-dev \
    libcanberra-gtk-module-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk0-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-dev \
    libcanberra-gtk3-0-dev \
    libcanberra-gtk3-module
